create table CATEGORIA{
	
		ID INT NOT NULL IDENTITY
		,NOME STRING NOT NULL
		, CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID)

};


create table PRODUTO{

	ID INT NOT NULL IDENTITY
	,NOME CHAR(50) NOT NULL
	,CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)


};

alter table PRODUTO ADD CONSTRAINT FK_PRODUTO_CATEGORIA  FOREIGN KEY (IDCategoria) REFERENCES CATEGORIA(ID);

INSERT INTO CATEGORIA(ID, NOME) VALUES
	(1, 'ESPORTE')
	,(2, 'INFORMATICA')
	,(3, 'ELETRONICO')
	,(4, 'LIVROS')
	,(5,'TELEFONIA')
	
	
INSERT INTO PRODUTO(ID, NOME, IDCategoria) VALUES
	(1, 'BICLETA',1 )
	,(2, 'NOTEBOOK',2)
	,(3, 'MOUSE SEM FIO', 2)
	,(4, 'TECLADO GAMER', 2)
	,(5, 'MICRO-SYSTEM', 3)
	,(6, 'SKATE', 1)
	
	
	

SELECT CATEGORIA.NOME as categoria, COUNT(PRODUTO.NOME) as qtdProduto FROM CATEGORIA
LEFT JOIN PRODUTO ON PRODUTO.IDCategoria = CATEGORIA.ID
GROUP BY CATEGORIA.NOME
HAVING COUNT(PRODUTO.NOME)
ORDER BY CATEGORIA.NOME 

SELECT CATEGORIA.NOME FROM PRODUTO
RIGHT JOIN  CATEGORIA ON PRODUTO.IDCategoria = CATEGORIA.ID
WHERE PRODUTO.ID IS NULL
ORDER BY CATEGORIA.NOME

SELECT PRODUTO.NOME, CATEGORIA.NOME FROM CATEGORIA
INNER JOIN PRODUTO ON PRODUTO.IDCategoria = CATEGORIA.ID
WHERE CATEGORIA.NOME  LIKE  ‘E%’
ORDER BY CATEGORIA.NOME, PRODUTO,NOME;

SELECT CATEGORIA.NOME,  COUNT(PRODUTO.IDCategoria) FROM CATEGORIA
INNER JOIN PRODUTO ON CATEGORIA.ID = PRODUTO.IDCategoria
GROUP BY CATEGORIA.NOME, COUNT(PRODUTO.IDCategoria ) 
HAVING COUNT(PRODUTO.ID)  >= 2
ORDER BY CATEGORIA.NOME;
SELECT  COUNT(CATEGORIA.NOME) as QTDCategoria FROM CATEGORIA
LEFT JOIN PRODUTO ON PRODUTO.IDCategoria = CATEGORIA.ID

SELECT COUNT(CATEGORIA.NOME)  AS QTDCATEGORIA
FROM PRODUTO
RIGHT JOIN  CATEGORIA ON PRODUTO.IDCategoria = CATEGORIA.ID
WHERE PRODUTO.ID IS NULL
ORDER BY QTDCATEGORIA
